configMap:
  db_host: expense-dev.cdmkkgg0knvp.us-east-1.rds.amazonaws.com
deployment:
  imageURL: 905418172435.dkr.ecr.us-east-1.amazonaws.com/expense/dev/backend
  imageVersion: IMAGE_VERSION
hpa:
  cpuUtilization: 20